require 'elixir/agent'
require 'elixir/atom'
require 'elixir/base'
require 'elixir/dict'
require 'elixir/enum'
require 'elixir/file'
require 'elixir/float'
require 'elixir/integer'
require 'elixir/list'
require 'elixir/option_parser'
require 'elixir/path'
require 'elixir/range'
require 'elixir/set'
require 'elixir/stream'
require 'elixir/string'
require 'elixir/system'
require 'elixir/task'
require 'elixir/tuple'
require 'elixir/version'

module Elixir
end
